---
- name: Config ELK stack server
  hosts: elk
  become: true
  tasks:

  - name: Increase virtual memory
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present
      reload: yes

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
